on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform run command'
        required: true
        type: choice
        options:
        - Plan 
        - Apply 
        - Destroy
      tfpath:
        description: 'TF File Path'     
        required: false
        default: './'
      instance_count: 
        description: 'Input the number of instances you want to create'
        required: true
        default: '1'

env: 
  db_table_name: shfarrukhb-finaltask-dynamodb
  s3_name: shfarrukhb-finaltask-bucket
 
jobs:
  Preparing_env:
    runs-on: ubuntu-latest
    if: ${{ inputs.tfpath }}
    
    steps:
    
    - uses: actions/checkout@v2.5.0
   
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Checking exsistance of tf files
      run: ls -la  
    
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2 

    - name: Check DB Existance
      run: | 
        if echo $(aws s3 ls | grep shfarrukhb-finaltask-state) == "" ; then
          echo "No"
        else
          echo "Exist"
        fi;
      working-directory: ./
    
      
      
        