on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform run command'
        required: true
        type: choice
        options:
        - terraform plan --lock-state=false
        - terraform apply --auto-approve --lock-state=false
        - terraform destroy --lock-state=false
      tfpath:
        description: 'TF File Path'     
        required: false
        default: './'
      instance_count: 
        description: 'Input the number of instances you want to create'
        required: true
        default: '3'


jobs:
  tf_code_check:
    name: Final task in actions
    runs-on: ubuntu-latest

    if:  ${{ inputs.tfpath }} 
    steps:
    - uses: actions/checkout@v2.5.0
    
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Checking exsistance of tf files
      run: ls -la  
    - name: aws-cli installation
      run: |
         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         unzip awscliv2.zip
         sudo ./aws/install --update
         aws --version

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: S3 Creation
      run: |
          aws s3 mb s3://shfarrukhb-itech-final-task
          env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'eu-east-1'   

